// <auto-generated />
namespace ajaxTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class isdaone_added_to_task : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(isdaone_added_to_task));
        
        string IMigrationMetadata.Id
        {
            get { return "201906041941166_isdaone_added_to_task"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
